<?xml version="1.0" encoding="utf-8"?><Database Name="HRMS_DB" Class="HRMS_DBLinq2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\HRMS_DB.mdf;Integrated Security=True" SettingsObjectName="HRMS.My.MySettings" SettingsPropertyName="HRMS_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.People" Member="Peoples">
    <Type Name="People">
      <Column Name="people_id" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="people_index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="people_password" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="people_name" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="people_ic" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="people_DOB" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="people_gender" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="people_phone" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="people_email" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="people_address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="people_role" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="department_name" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="leave_num" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="extra_leave" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hourly_rates" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.attend" Member="attends">
    <Type Name="attend">
      <Column Name="attendance_id" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="people_id" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="[current_date]" Member="current_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="time_in" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="time_out" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="lunch_in" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="lunch_out" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.deduction" Member="deductions">
    <Type Name="deduction">
      <Column Name="deduction_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="deduction_type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="deduction_value" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="deduction_format" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="people_id" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="deduction_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Leave" Member="Leaves">
    <Type Name="Leave">
      <Column Name="leave_id" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="leave_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="apply_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="leave_duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reason" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="people_id" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Reject_approve_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.mandatory_deduction" Member="mandatory_deductions">
    <Type Name="mandatory_deduction">
      <Column Name="deduction_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="deduction_type" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="deduction_value" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="deduction_format" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.netpay" Member="netpays">
    <Type Name="netpay">
      <Column Name="payroll_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="people_id" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="total_attendance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_absence" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="final_pay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="generated_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ttl_mandatory_ddt" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ttl_deduction" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.overtime" Member="overtimes">
    <Type Name="overtime">
      <Column Name="overtime_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="people_id" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="overtime_duration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="overtime_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>